ci:
  autofix_commit_msg: "CI: Auto fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_commit_msg: "CI: Pre-commit autoupdate"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-toml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
    -   id: ruff
        files: smudge
        args: [ --fix, --exit-non-zero-on-fix ]

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        files: smudge
